# Generated by Django 4.2.5 on 2023-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_class', models.CharField(max_length=20)),
                ('parent_name1', models.CharField(max_length=100)),
                ('parent_name2', models.CharField(max_length=100)),
                ('parent_phone_number1', models.CharField(max_length=20)),
                ('parent_phone_number2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('swietlica', models.CharField(choices=[('tak', 'Tak'), ('nie', 'Nie')], max_length=20)),
                ('payment', models.CharField(choices=[('semestralnie', 'Semestralnie'), ('za każde zajecia', 'Za każde zajęcia')], max_length=20)),
            ],
        ),
    ]
